### ISSUE TITLE
Creating Zip failes due to filesize

### ISSUE THREAD

**Issue by jsnet-ops** [Kentico/kontent-backup-manager-js#17]
At the "Create zip file" stage following error occurs:

There was an error processing your request:  RangeError [ERR_INVALID_ARG_VALUE]: The argument 'size' is invalid. Received 4620737532
    at Function.allocUnsafe (node:buffer:374:3)
    at Function.concat (node:buffer:553:25)
    at concat (/usr/lib/node_modules/@kentico/kontent-backup-manager/node_modules/jszip/lib/stream/StreamHelper.js:62:27)
    at StreamHelper.<anonymous> (/usr/lib/node_modules/@kentico/kontent-backup-manager/node_modules/jszip/lib/stream/StreamHelper.js:96:61)
    at Immediate._onImmediate (/usr/lib/node_modules/@kentico/kontent-backup-manager/node_modules/jszip/lib/utils.js:381:18)
    at processImmediate (node:internal/timers:464:21) {
  code: 'ERR_INVALID_ARG_VALUE'
}

This seems to be JSZip related, although size is not a known restriction.
- Zip to be written: 4.6GB
- Diskspace: 230GB

Versions used:
Ubuntu 20.04 (In Docker)
Node: v16.1.0
npm: 7.11.2
jszip: 3.6.0

**Comment by sojwil** [comment]
Hi Enngage,

Thanks for your help.
As recommended, I started the backup like this:

`node --max-old-space-size=8192 ./_commonjs/src/node-js/cli/app.js --action=backup --apiKey=xxx --projectId=xxxx --zipFilename=bak`

Also, I added some extra debug info to zip.service.ts to make sure the right amount is memory (8192) is allocated and no overruns occur. Still the same error msg.

Any other suggestions are very welcome.
